---
- hosts: k3s_rpi_master
  remote_user: pi
  become: True
  gather_facts: True

  tasks:
    - name: Test csa
      template:
        src: "a.txt"
        dest: "/etc/a.txt"
        owner: "root"
        group: "root"
        mode: 0644
