apiVersion: v1
kind: Service
metadata:
  name: ser-node
spec:
  selector:
    app: node-test
    tier: backend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-test
spec:
  selector:
    matchLabels:
      app: node-test
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: node-test
        tier: backend
        track: stable
    spec:
      containers:
      - name: node-test
        image: fullstackjs-tmp:Dockerfile
