apiVersion: v1
kind: Service
metadata:
  name: ser-db
spec:
  selector:
    app: db-postgres
    tier: backend
  ports:
  - protocol: TCP
    port: 3211
    targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-postgres
spec:
  selector:
    matchLabels:
      app: db-postgres
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: db-postgres
        tier: backend
        track: stable
    spec:
      containers:
        - name: db-postgres
          image: postgrescsa:Dockerfile
          ports:
            - name: http
              containerPort: 3211

